export const INITIALIZE_STATE = 'INITIALIZE_STATE';
export const HIDE_WELCOME = 'HIDE_WELCOME';

export const DELETE_MODIFIER = 'MODIFIERS/DELETE';
export const LOAD_MODIFIERS = 'MODIFIERS/LOAD';
export const EDIT_MODIFIER = 'MODIFIERS/EDIT';
export const ADD_MODIFIER = 'MODIFIERS/ADD';

export const DELETE_MESSAGE = 'MESSAGES/DELETE';
export const LOAD_MESSAGES = 'MESSAGES/LOAD';

export const DELETE_FILTER = 'FILTERS/DELETE';
export const LOAD_FILTERS = 'FILTERS/LOAD';
export const EDIT_FILTER = 'FILTERS/EDIT';
export const ADD_FILTER = 'FILTERS/ADD';

export const DELETE_EMAIL = 'EMAILS/DELETE';
export const LOAD_EMAILS = 'EMAILS/LOAD';

export const ADD_DOMAIN = 'DOMAINS/ADD';

export const DELETE_PRIMARY_EMAIL = 'ACCOUNT/DELETE_EMAIL';
export const SET_EMAIL_TEMPLATE = 'ACCOUNT/SET_EMAIL_TEMPLATE';
export const ADD_PRIMARY_EMAIL = 'ACCOUNT/ADD_EMAIL';
export const UPDATE_CREDITS = 'ACCOUNT/UPDATE_CREDITS';
