-- Add default values
ALTER TABLE `aliases` CHANGE `name` `name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Untitled Alias', CHANGE `created` `created` INT(10) UNSIGNED NOT NULL DEFAULT '0', CHANGE `smtpKey` `smtpKey` VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', CHANGE `saveMail` `saveMail` TINYINT(1) NOT NULL DEFAULT '0', CHANGE `canReply` `canReply` TINYINT(1) NOT NULL DEFAULT '0';
ALTER TABLE `domains` CHANGE `selector` `selector` VARCHAR(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', CHANGE `created` `created` INT(10) UNSIGNED NOT NULL DEFAULT '0', CHANGE `verified` `verified` TINYINT(1) NOT NULL DEFAULT '0', CHANGE `global` `global` TINYINT(1) NOT NULL DEFAULT '0';
ALTER TABLE `domain_users` CHANGE `label` `label` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Domain User', CHANGE `requestKey` `requestKey` VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', CHANGE `created` `created` INT(10) UNSIGNED NOT NULL DEFAULT '0', CHANGE `authorized` `authorized` TINYINT(1) NOT NULL DEFAULT '0';
ALTER TABLE `filters` CHANGE `name` `name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Untitled Filter', CHANGE `type` `type` VARCHAR(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'text', CHANGE `find` `find` VARCHAR(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', CHANGE `blacklist` `blacklist` TINYINT(1) NOT NULL DEFAULT '0', CHANGE `regex` `regex` TINYINT(1) NOT NULL DEFAULT '0', CHANGE `created` `created` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `links` CHANGE `orderIndex` `orderIndex` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `messages` CHANGE `key` `key` VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '', CHANGE `created` `created` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `modifiers` CHANGE `name` `name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Untitled Modifier', CHANGE `target` `target` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'text', CHANGE `created` `created` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `payments` CHANGE `tier` `tier` VARCHAR(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'basic', CHANGE `duration` `duration` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'month', CHANGE `amount` `amount` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `primary_emails` CHANGE `address` `address` VARCHAR(320) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', CHANGE `created` `created` INT(10) UNSIGNED NOT NULL DEFAULT '0', CHANGE `key` `key` VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', CHANGE `verified` `verified` TINYINT(1) NOT NULL DEFAULT '0', CHANGE `autolink` `autolink` TINYINT(1) NOT NULL DEFAULT '0';