export const CREATE_REDIRECT_EMAIL = 'EMAILS/CREATE';
export const LIST_REDIRECT_EMAILS = 'EMAILS/LIST';
export const EDIT_REDIRECT_EMAIL = 'EMAILS/EDIT';

export const LIST_MESSAGES = 'EMAILS/MESSAGES/LIST';
export const VIEW_MESSAGE = 'EMAILS/MESSAGES/VIEW';
export const SEND_MESSAGE = 'EMAILS/MESSAGES/SEND';

export const CREATE_MODIFIER = 'MODIFIERS/CREATE';
export const LIST_MODIFIERS = 'MODIFIERS/LIST';
export const EDIT_MODIFIER = 'MODIFIERS/EDIT';

export const CREATE_FILTER = 'FILTERS/CREATE';
export const LIST_FILTERS = 'FILTERS/LIST';
export const EDIT_FILTER = 'FILTERS/EDIT';

export const PURCHASE_SUBSCRIPTION = 'ACCOUNT/PURCHASE_SUBSCRIPTION';
export const ACCOUNT = 'ACCOUNT';

export const HELP_DOCS = 'DOCS';