export const CREATE_REDIRECT_EMAIL = 'EMAILS/CREATE';
export const LIST_REDIRECT_EMAILS = 'EMAILS/LIST';
export const EDIT_REDIRECT_EMAIL = 'EMAILS/EDIT';

export const LIST_MESSAGES = 'EMAILS/MESSAGES/LIST';
export const VIEW_MESSAGE = 'EMAILS/MESSAGES/VIEW';
export const SEND_MESSAGE = 'EMAILS/MESSAGES/SEND';

export const CREATE_MODIFIER = 'MODIFIERS/CREATE';
export const LIST_MODIFIERS = 'MODIFIERS/LIST';
export const EDIT_MODIFIER = 'MODIFIERS/EDIT';

export const CREATE_FILTER = 'FILTERS/CREATE';
export const LIST_FILTERS = 'FILTERS/LIST';
export const EDIT_FILTER = 'FILTERS/EDIT';

export const PURCHASE_CREDITS = 'ACCOUNT/CREDITS/PURCHASE';
export const PRIMARY_EMAILS = 'ACCOUNT/PRIMARY_EMAILS';
export const EARN_CREDITS = 'ACCOUNT/CREDITS/EARN';
export const ACCOUNT = 'ACCOUNT';

export const DOCUMENTATION = 'DOCS';

export const QUICK_SEARCH = 'QUICK_SEARCH';

export const LIST_DOMAINS = 'DOMAINS/LIST';
export const VIEW_DOMAIN = 'DOMAINS/VIEW';
export const ADD_DOMAIN = 'DOMAINS/ADD';
